### ISSUE TITLE
ZenProperty annotation not behaving properly

### ISSUE THREAD

**Issue by TeamDman** [CraftTweaker/ZenScript#24]
NOT working
![](https://i.imgur.com/coSq2qM.png)
Also did not work when the annotation parameters were omitted 

WORKING
![](https://i.imgur.com/i52BlHM.png)

The ZenProperty documentation also states that the `getter` and `setter` properties can be null to prevent the methods from being registered, but annotations do not accept null values, and there is no code to handle the case in the implementation anyways

Relevant Links
https://crafttweaker.readthedocs.io/en/latest/#Dev_Area/ZenAnnotations/ZenMembers/#zenproperty
https://discordapp.com/channels/136877912698650625/415842429384654862/550474425766772756

**Comment by jaredlll08** [comment]
Your fields need to be public, not package private...
