### ISSUE TITLE
[Bug] "unexpected end of file - ; expected" when trying to iterate over loadedMods

### ISSUE THREAD

**Issue by CREEATION** [CraftTweaker/ZenScript#27]
#### Issue Description:
Trying to get a list of all mods doesn't work.

#### What happens:
`[INITIALIZATION][CLIENT][ERROR] :1 > unexpected end of file - ; expected`

#### What you expected to happen:
List all mods in the log.

#### Script used:
[script file](https://pastebin.com/FVhfAdqT)

```
import crafttweaker.mods.ILoadedMods;
 
print("listing mods...");
 
for mod in loadedMods {
    print( mod.id ~ " + " ~ mod.name );
}
 
print("done!");
```

#### crafttweaker.log file:
[crafttweaker.log](https://pastebin.com/S69JK2NG)

____
#### Affected Versions:

- Minecraft: `1.12.2`
- Forge: `14.23.5.2776`
- Crafttweaker: `4.1.15`
- Using a server: no

**Comment by kindlich** [comment]
Transfered to ZS because that's a (known) ZS issue.
Fixed in an upcoming PR
