### ISSUE TITLE
break keyword returns to the first loop in a given function

### ISSUE THREAD

**Issue by Sargeanthost** [CraftTweaker/ZenScript#48]
Refer to below images:

![image](https://user-images.githubusercontent.com/36427968/211202088-62bf6149-5af9-4924-8b0a-017df0da9ff0.png)
![image](https://user-images.githubusercontent.com/36427968/211202089-fb7ee868-950b-4419-afda-a6a142112b0c.png)
![image](https://user-images.githubusercontent.com/36427968/211202091-720c77b8-e040-461f-826a-e42a8e81780e.png)

It seems like the break keyword jumps to the end of the first for statement in the function, as rand gets reassigned and "SOW" prints again. This currently bricks the game as it runs an infinite loop (this should aslo be an enhancement as zs should detect infinite loops and, if anything, just break and log the loop and cause unintended behavior--instead of freezing the game)

Edit: ignore the youtube link that was for my reference.

**Comment by jaredlll08** [comment]
What MC version are you using?

**Comment by Sargeanthost** [comment]
1.18.2

**Comment by jaredlll08** [comment]
This is the wrong repo then, I remade your issue on the correct one here:
https://github.com/ZenCodeLang/ZenCode/issues/112
